version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
